/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Sneaker = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'sizes' : IDL.Vec(IDL.Text),
  'isFeatured' : IDL.Bool,
  'category' : IDL.Text,
  'price' : IDL.Float64,
});

export const idlService = IDL.Service({
  'getAllSneakers' : IDL.Func([], [IDL.Vec(Sneaker)], ['query']),
  'getFeaturedSneakers' : IDL.Func([], [IDL.Vec(Sneaker)], ['query']),
  'getSneakerById' : IDL.Func([IDL.Nat], [Sneaker], ['query']),
  'seedSneakers' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Sneaker = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'sizes' : IDL.Vec(IDL.Text),
    'isFeatured' : IDL.Bool,
    'category' : IDL.Text,
    'price' : IDL.Float64,
  });
  
  return IDL.Service({
    'getAllSneakers' : IDL.Func([], [IDL.Vec(Sneaker)], ['query']),
    'getFeaturedSneakers' : IDL.Func([], [IDL.Vec(Sneaker)], ['query']),
    'getSneakerById' : IDL.Func([IDL.Nat], [Sneaker], ['query']),
    'seedSneakers' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };